yarnPath: ".yarn/releases/yarn-berry.cjs"

#packageExtensions:
#  "@pmmmwh/react-refresh-webpack-plugin@*":
#    peerDependencies:
#      webpack: ^5.0.0
#  "razzle@*":
#    dependencies:
#      postcss-load-config: ^2.0.0

